policies:
  - name: echo-policy
    host: echo.localtest.me
    mode: prevent-learn

    accessControl:
      rateLimit:
        rules:
          - action: inherited
            uri: /rate
            limit: 3
            unit: minute

    exceptions:
      - name: allow-rule
        host: echo.localtest.me/allowed
        action: accept
        conditions:
          - key: url
            value: /allowed
      - name: drop-rule
        host: echo.localtest.me/blocked
        action: drop
        conditions:
          - key: url
            value: /blocked
      - name: skip-rule
        host: echo.localtest.me/skip
        action: skip
        conditions:
          - key: paramName
            value: ignored
      - name: suppress-log-rule
        host: echo.localtest.me/quiet
        action: suppressLog
        conditions:
          - key: url
            value: /quiet
