ingressController:
  ingressClass: appsec-kong

proxy:
  type: NodePort
  http:
    nodePort: 30080
    containerPort: 80
  tls:
    nodePort: 30443
    containerPort: 443

appsec:
  persistence:
    enabled: false

env:
  proxy_listen: "0.0.0.0:80 reuseport backlog=16384, 0.0.0.0:443 http2 ssl reuseport backlog=16384"

containerSecurityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
