apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: lab
spec:
  ingressClassName: appsec-kong
  rules:
    - host: echo.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
